import { status } from './constants';

const orders = [
  {
    id: '1',
    tableId: '100',
    articleId: '100',
    groupId: '10',
    status: status.PREPARING,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '2',
    tableId: '100',
    articleId: '220',
    groupId: '15',
    status: status.PREPARING,
    toDo: 1,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '3',
    tableId: '100',
    articleId: '101',
    groupId: '10',
    status: status.PREPARING,
    toDo: 1,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '4',
    tableId: '100',
    articleId: '500',
    groupId: '50',
    status: status.ORDERED,
    toDo: 1,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '5',
    tableId: '100',
    articleId: '501',
    groupId: '50',
    status: status.ORDERED,
    toDo: 1,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '6',
    tableId: '100',
    articleId: '522',
    groupId: '50',
    status: status.ORDERED,
    toDo: 1,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '7',
    tableId: '100',
    articleId: '601',
    groupId: '70',
    status: status.ORDERED,
    toDo: 1,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '8',
    tableId: '100',
    articleId: '620',
    groupId: '70',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '20',
    tableId: '102',
    articleId: '100',
    groupId: '10',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '9',
    tableId: '102',
    articleId: '220',
    groupId: '15',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '10',
    tableId: '102',
    articleId: '101',
    groupId: '10',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '11',
    tableId: '102',
    articleId: '400',
    groupId: '30',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '12',
    tableId: '102',
    articleId: '401',
    groupId: '30',
    status: status.ORDERED,
    toDo: 4,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '13',
    tableId: '102',
    articleId: '501',
    groupId: '50',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '14',
    tableId: '102',
    articleId: '521',
    groupId: '50',
    status: status.ORDERED,
    toDo: 3,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '15',
    tableId: '102',
    articleId: '522',
    groupId: '50',
    status: status.ORDERED,
    toDo: 1,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '16',
    tableId: '102',
    articleId: '620',
    groupId: '70',
    status: status.ORDERED,
    toDo: 5,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '17',
    tableId: '102',
    articleId: '601',
    groupId: '70',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
  {
    id: '18',
    tableId: '102',
    articleId: '600',
    groupId: '70',
    status: status.ORDERED,
    toDo: 2,
    done: 0,
    orderTime: 0,
    timeToStartToPrepare: '',
  },
];

export default orders;
